version: 1.0.{build}
image: Visual Studio 2017

build_script:
- cmd: |
    msbuild src\InlineIL.sln /v:m /t:Restore,Rebuild /p:Configuration=Debug
    msbuild src\InlineIL.sln /v:m /t:Rebuild,Pack /p:Configuration=Release

test_script:
- cmd: |
    dotnet test src\InlineIL.Tests\InlineIL.Tests.csproj --no-build --configuration Debug
    dotnet test src\InlineIL.Tests\InlineIL.Tests.csproj --no-build --configuration Release

artifacts:
- path: output\**\*.nupkg
