version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: |
    nuget restore src\InlineIL.sln

build_script:
- cmd: |
    msbuild src\InlineIL.sln             /t:Rebuild /v:m /p:Configuration=Release
    msbuild src\InlineIL\InlineIL.csproj /t:Rebuild /v:m /p:Configuration=Release /p:GenerateNuGetPackage=true

test_script:
- cmd: |
    %xunit20%\xunit.console src\InlineIL.Tests\bin\Release\net46\InlineIL.Tests.dll -appveyor
    dotnet test "src\InlineIL.Tests\InlineIL.Tests.csproj" --framework netcoreapp2.0 --configuration Release --no-build --output bin\Release\netcoreapp2.0

artifacts:
- path: output\**\*.nupkg
