
variables:
  Solution: src/InlineIL.sln
  TestProject: src/InlineIL.Tests/InlineIL.Tests.csproj

jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - task: DotNetCoreInstaller@1
        displayName: Install .NET Core SDK
        inputs:
          version: 3.0.x

      - task: DotNetCoreCLI@2
        displayName: Build Debug
        inputs:
          command: build
          projects: $(Solution)
          arguments: --configuration Debug

      - task: DotNetCoreCLI@2
        displayName: Build Release
        inputs:
          command: build
          projects: $(Solution)
          arguments: --configuration Release

      - task: DotNetCoreCLI@2
        displayName: NuGet Pack
        inputs:
          command: pack
          packagesToPack: $(Solution)
          configuration: Release
          nobuild: true
          verbosityPack: Minimal

      - task: DotNetCoreCLI@2
        displayName: Test Debug
        continueOnError: true
        inputs:
          command: test
          projects: $(TestProject)
          arguments: --configuration Debug
          nobuild: true
          testRunTitle: Debug

      - task: DotNetCoreCLI@2
        displayName: Test Release
        continueOnError: true
        inputs:
          command: test
          projects: $(TestProject)
          arguments: --configuration Release
          nobuild: true
          testRunTitle: Release

      - task: PublishBuildArtifacts@1
        displayName: Publish Debug Artifacts
        inputs:
          ArtifactName: Debug
          pathToPublish: src/InlineIL.Tests/bin

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          ArtifactName: NuGet
